//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::Deserialize;
use validator::Validate;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel,Deserialize,Validate)]
#[sea_orm(table_name = "attended_meetings")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub meeting_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    #[validate(email)]
    pub student_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub subject_id: i32,
    #[sea_orm(column_type = "Float")]
    #[validate(range(exclusive_min = 0.0, max = 100.0))]
    pub percentage: f32,
}

#[derive(Clone,Deserialize,Validate,DeriveIntoActiveModel)]
pub struct ModelId{
    pub meeting_id: i32,
    #[validate(email)]
    pub student_id: String,
    pub subject_id: i32,
}


#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::meetings::Entity",
        from = "Column::MeetingId",
        to = "super::meetings::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Meetings,
    #[sea_orm(
        belongs_to = "super::subjects_attendies::Entity",
        from = "(Column::StudentId, Column::SubjectId)",
        to = "(super::subjects_attendies::Column::StudentId, super::subjects_attendies::Column::SubjectId)",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    SubjectsAttendies,
}

impl Related<super::meetings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Meetings.def()
    }
}

impl Related<super::subjects_attendies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SubjectsAttendies.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
