//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::Deserialize;
use validator::Validate;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "logs")]
pub struct Model {
    #[sea_orm(primary_key, unique)]
    pub id: i32,
    pub time: DateTime,
    #[sea_orm(column_type = "Text")]
    pub description: String,
}

#[derive(Clone, Debug, Deserialize,Validate)]
pub struct ModelQuery{
    pub time_lowerbound: Option<DateTime>,
    pub time_upperbound: Option<DateTime>,
    pub event: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
