//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub mod accounts;
pub mod assignments;
pub mod assignments_marks;
pub mod attended_meetings;
pub mod logs;
pub mod meetings;
pub mod students;
pub mod subjects;
pub mod subjects_attendies;
pub mod teachers;
pub mod users;
