//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::accounts::Entity as Accounts;
pub use super::assignments::Entity as Assignments;
pub use super::assignments_marks::Entity as AssignmentsMarks;
pub use super::attended_meetings::Entity as AttendedMeetings;
pub use super::logs::Entity as Logs;
pub use super::meetings::Entity as Meetings;
pub use super::students::Entity as Students;
pub use super::subjects::Entity as Subjects;
pub use super::subjects_attendies::Entity as SubjectsAttendies;
pub use super::teachers::Entity as Teachers;
pub use super::users::Entity as Users;
