//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "subjects")]
pub struct Model {
    #[sea_orm(primary_key, unique)]
    pub id: i32,
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub semestr: Option<i32>,
    pub teacher_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::assignments::Entity")]
    Assignments,
    #[sea_orm(has_many = "super::meetings::Entity")]
    Meetings,
    #[sea_orm(has_many = "super::subjects_attendies::Entity")]
    SubjectsAttendies,
    #[sea_orm(
        belongs_to = "super::teachers::Entity",
        from = "Column::TeacherId",
        to = "super::teachers::Column::Email",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Teachers,
}

impl Related<super::assignments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Assignments.def()
    }
}

impl Related<super::meetings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Meetings.def()
    }
}

impl Related<super::subjects_attendies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SubjectsAttendies.def()
    }
}

impl Related<super::teachers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Teachers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
